//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PilMoneyBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra_venta_Divisas
    {
        public int id_tipo { get; set; }
        public int id_extraccion { get; set; }
        public int id_deposito { get; set; }
        public decimal monto { get; set; }
        public int id_moneda { get; set; }
    
        public virtual Deposito Deposito { get; set; }
        public virtual Extraccione Extraccione { get; set; }
        public virtual tipo_moneda tipo_moneda { get; set; }
        public virtual Tipos_dep_extr Tipos_dep_extr { get; set; }
    }
}
