//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deposito()
        {
            this.compra_venta_Divisas = new HashSet<compra_venta_Divisas>();
            this.Operaciones = new HashSet<Operacione>();
        }
    
        public int id_deposito { get; set; }
        public string cod_seguridad { get; set; }
        public int id_tipo { get; set; }
        public decimal monto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra_venta_Divisas> compra_venta_Divisas { get; set; }
        public virtual Tipos_dep_extr Tipos_dep_extr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacione> Operaciones { get; set; }
    }
}
