//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PilPayEntities : DbContext
    {
        public PilPayEntities()
            : base("name=PilPayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuenta> Cuentas { get; set; }
        public virtual DbSet<Deposito> Depositos { get; set; }
        public virtual DbSet<domicilio> domicilios { get; set; }
        public virtual DbSet<Eleccione> Elecciones { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Extraccione> Extracciones { get; set; }
        public virtual DbSet<formaDePago> formaDePagoes { get; set; }
        public virtual DbSet<Inversione> Inversiones { get; set; }
        public virtual DbSet<Operacione> Operaciones { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Rendimiento> Rendimientos { get; set; }
        public virtual DbSet<Tarjeta> Tarjetas { get; set; }
        public virtual DbSet<tipo_moneda> tipo_moneda { get; set; }
        public virtual DbSet<Tipos_dep_extr> Tipos_dep_extr { get; set; }
        public virtual DbSet<Transferencia> Transferencias { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<compra_venta_Divisas> compra_venta_Divisas { get; set; }
        public virtual DbSet<Contacto> Contactos { get; set; }
    }
}
