//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacione
    {
        public int id_operacion { get; set; }
        public Nullable<int> CVU { get; set; }
        public Nullable<System.DateTime> fecha_operacion { get; set; }
        public Nullable<System.TimeSpan> hora_oprecion { get; set; }
        public Nullable<int> id_deposito { get; set; }
        public Nullable<int> id_extraccion { get; set; }
        public Nullable<int> id_transferencia { get; set; }
        public Nullable<int> id_inversion { get; set; }
        public Nullable<int> id_pago { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Deposito Deposito { get; set; }
        public virtual Extraccione Extraccione { get; set; }
        public virtual Inversione Inversione { get; set; }
        public virtual Pago Pago { get; set; }
        public virtual Transferencia Transferencia { get; set; }
    }
}
