//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjeta()
        {
            this.Personas = new HashSet<Persona>();
        }
        [Required(ErrorMessage = "Dato requerido")]
        public string marca_TC { get; set; }
        [Key]
        [Required(ErrorMessage = "Dato requerido")]
        [MaxLength(16, ErrorMessage = "debe ingresar los 16 digitos")]
        
        public string nro_tarjeta { get; set; }
        [Required(ErrorMessage = "Dato requerido")]
        public string titular { get; set; }
        [Required(ErrorMessage = "Dato requerido")]
        public System.DateTime vencimiento { get; set; }
        [Required(ErrorMessage = "Dato requerido")]
        [MaxLength(3, ErrorMessage = "debe ingresar los 3 digitos")]
        public string CVV { get; set; }

        [MaxLength(8, ErrorMessage = "debe ingresar los 8 digitos")]
        [Required(ErrorMessage = "Dato requerido")]
        public int DNI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Persona> Personas { get; set; }
    }
}
